# Use the official Python image as base
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed dependencies specified in requirements.txt
RUN pip install -r requirements.txt

# Copy the Python file into the container at /app
COPY chat_ui.py .

# Expose port
EXPOSE 80

# Run UI server
CMD ["chainlit", "run", "chat_ui.py", "-w", "--host", "0.0.0.0", "--port", "80"]
